//this file is for testing small js programms before using them in big projects
//feel free to use it...
const prompt=require('prompt-sync')();
const num=prompt('enter a number\n');
console.log(num);
//working......
//success....
//previously i had to use readline interface ...
//nut now prompt works
//at 1st i had to give a command at cmd to install additional packages
//go to cmd and write
//$ npm install prompt-sync